### ISSUE TITLE
Question about `retain_intermediate_artifacts` option

### ISSUE THREAD

**Issue by skyshine102** [joshua-auchincloss/hatch-cython#25]
I had a problem when I specified the following in the repo example:

[build.hooks.custom.options]
retain_intermediate_artifacts = **False**

The error shows:
![image](https://github.com/joshua-auchincloss/hatch-cython/assets/7519404/3194e07a-19eb-4c12-a07a-1e29e6bc1b19)

Is this the expected behavior? How can I work around this problem?

**Comment by joshua-auchincloss** [comment]
Hey sorry for the delayed response - looks like a bug. Will be patched & tested for regression in future revisions 👍
